// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1taiWn4ws3jWgGZvSCZ_cSicDC2if6w',
    appId: '1:1036411005507:web:ffe9cb53a42dc0f299c2f6',
    messagingSenderId: '1036411005507',
    projectId: 'flare-dating-app-eb907',
    authDomain: 'flare-dating-app-eb907.firebaseapp.com',
    storageBucket: 'flare-dating-app-eb907.firebasestorage.app',
    measurementId: 'G-2XFFFGDH2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYPYy4um7LAAm0e5isNjYwyiqqhAw7xAI',
    appId: '1:1036411005507:android:86bd004c8d35b10199c2f6',
    messagingSenderId: '1036411005507',
    projectId: 'flare-dating-app-eb907',
    storageBucket: 'flare-dating-app-eb907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY5SjYscW-JKxHLUUGTrqeaE8KjwWv1wc',
    appId: '1:1036411005507:ios:7ecfc6184ddb975f99c2f6',
    messagingSenderId: '1036411005507',
    projectId: 'flare-dating-app-eb907',
    storageBucket: 'flare-dating-app-eb907.firebasestorage.app',
    iosBundleId: 'com.example.flareDatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY5SjYscW-JKxHLUUGTrqeaE8KjwWv1wc',
    appId: '1:1036411005507:ios:7ecfc6184ddb975f99c2f6',
    messagingSenderId: '1036411005507',
    projectId: 'flare-dating-app-eb907',
    storageBucket: 'flare-dating-app-eb907.firebasestorage.app',
    iosBundleId: 'com.example.flareDatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu1taiWn4ws3jWgGZvSCZ_cSicDC2if6w',
    appId: '1:1036411005507:web:519e166cd4e8192c99c2f6',
    messagingSenderId: '1036411005507',
    projectId: 'flare-dating-app-eb907',
    authDomain: 'flare-dating-app-eb907.firebaseapp.com',
    storageBucket: 'flare-dating-app-eb907.firebasestorage.app',
    measurementId: 'G-F4EXJQ2486',
  );
}
